/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppFarmRouteImport } from './routes/app.farm'
import { Route as AppNasaRouteImport } from './routes/app.nasa'
import { Route as AppSoilRouteImport } from './routes/app.soil'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppFarmRoute = AppFarmRouteImport.update({
  id: '/farm',
  path: '/farm',
  getParentRoute: () => AppRoute,
} as any)
const AppNasaRoute = AppNasaRouteImport.update({
  id: '/nasa',
  path: '/nasa',
  getParentRoute: () => AppRoute,
} as any)
const AppSoilRoute = AppSoilRouteImport.update({
  id: '/soil',
  path: '/soil',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/farm': typeof AppFarmRoute
  '/app/nasa': typeof AppNasaRoute
  '/app/soil': typeof AppSoilRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/farm': typeof AppFarmRoute
  '/app/nasa': typeof AppNasaRoute
  '/app/soil': typeof AppSoilRoute
  '/app': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/app/farm': typeof AppFarmRoute
  '/app/nasa': typeof AppNasaRoute
  '/app/soil': typeof AppSoilRoute
  '/app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app' | '/app/farm' | '/app/nasa' | '/app/soil' | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app/farm' | '/app/nasa' | '/app/soil' | '/app'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/farm'
    | '/app/nasa'
    | '/app/soil'
    | '/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/farm': {
      id: '/app/farm'
      path: '/farm'
      fullPath: '/app/farm'
      preLoaderRoute: typeof AppFarmRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/nasa': {
      id: '/app/nasa'
      path: '/nasa'
      fullPath: '/app/nasa'
      preLoaderRoute: typeof AppNasaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/soil': {
      id: '/app/soil'
      path: '/soil'
      fullPath: '/app/soil'
      preLoaderRoute: typeof AppSoilRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppFarmRoute: typeof AppFarmRoute
  AppNasaRoute: typeof AppNasaRoute
  AppSoilRoute: typeof AppSoilRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppFarmRoute: AppFarmRoute,
  AppNasaRoute: AppNasaRoute,
  AppSoilRoute: AppSoilRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
